# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

version = 1

[[annotations]]
path = "charts/matrix-stack/sub_schemas/*.json"
SPDX-FileCopyrightText = "Copyright 2024 New Vector Ltd"
SPDX-License-Identifier = "AGPL-3.0-only OR LicenseRef-Element-Commercial"

[[annotations]]
path = "charts/**/values.schema.json"
SPDX-FileCopyrightText = "Copyright 2024 New Vector Ltd"
SPDX-License-Identifier = "AGPL-3.0-only OR LicenseRef-Element-Commercial"

[[annotations]]
path = "poetry.lock"
SPDX-FileCopyrightText = "Copyright 2024 New Vector Ltd"
SPDX-License-Identifier = "AGPL-3.0-only OR LicenseRef-Element-Commercial"

[[annotations]]
path = "scripts/testdata/**/*.json"
SPDX-FileCopyrightText = "Copyright 2024 New Vector Ltd"
SPDX-License-Identifier = "AGPL-3.0-only OR LicenseRef-Element-Commercial"
