{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with .Values.matrixAuthenticationService -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{ include "element-io.ess-library.postgres-annotation" (dict "root" $ "context" (dict
                                                                "postgresProperty" .postgres
                                                                "defaultSecretName" (printf "%s-matrix-authentication-service" $.Release.Name)
                                                                )
                                            ) -}}
{{- with .annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "element-io.matrix-authentication-service.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-matrix-authentication-service
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ $.Release.Name }}-matrix-authentication-service"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        {{- include "element-io.matrix-authentication-service.labels" (dict "root" $ "context" .) | nindent 8 }}
        k8s.element.io/confighash: "{{ include (print $.Template.BasePath "/matrix-authentication-service/secret.yaml") $ | sha1sum }}"
      annotations:
        {{ include "element-io.ess-library.postgres-annotation" (dict "root" $ "context" (dict
                                                                "postgresProperty" .postgres
                                                                "defaultSecretName" (printf "%s-matrix-authentication-service" $.Release.Name)
                                                                )
                                            ) -}}
{{- with .annotations }}
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- if gt (.replicas | int) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - "{{ $.Release.Name }}-matrix-authentication-service"
            topologyKey: kubernetes.io/hostname
{{- end }}
{{- include "element-io.ess-library.pods.commonSpec" (dict "root" $ "context" (dict "componentValues" . "key" "matrix-authentication-service" "deployment" true "usesMatrixTools" true)) | nindent 6 }}
      initContainers:
      - name: render-config
{{- with $.Values.matrixTools.image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ required "synapse.image.tag is required if no digest" .tag }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        command:
        - "/matrix-tools"
        - render-config
        - -output
        - /conf/config.yaml
          {{- range $key := (.additional | keys | uniq | sortAlpha) -}}
          {{- $prop := index $.Values.matrixAuthenticationService.additional $key }}
          {{- if $prop.config }}
        - /secrets/{{ $.Release.Name }}-matrix-authentication-service/user-{{ $key }}
          {{- end }}
          {{- if $prop.configSecret }}
        - /secrets/{{ tpl $prop.configSecret $ }}/{{ $prop.configSecretKey }}
          {{- end }}
          {{- end }}
        - /config-templates/config.yaml
        env:
        - name: POSTGRES_PASSWORD
          value: >-
            {{
              printf "{{ readfile \"/secrets/%s\" | urlencode }}" (
                 include "element-io.ess-library.postgres-secret-path" (
                     dict "root" $
                     "context" (dict
                       "secretProperty" .postgres.password
                       "defaultSecretName" (printf "%s-matrix-authentication-service" $.Release.Name)
                       "defaultSecretKey" "POSTGRES_PASSWORD"
                     )
                  )
                )
            }}
        - name: ENCRYPTION_SECRET
          value: >-
            {{
              printf "{{ readfile \"/secrets/%s\" | quote }}" (
                 include "element-io.ess-library.init-secret-path" (
                     dict "root" $
                     "context" (dict
                       "secretProperty" .encryptionSecret
                       "initSecretKey" "MAS_ENCRYPTION_SECRET"
                       "defaultSecretName" (printf "%s-matrix-authentication-service" $.Release.Name)
                       "defaultSecretKey" "ENCRYPTION_SECRET"
                     )
                  )
                )
            }}
{{- if $.Values.synapse.enabled }}
        - name: SYNAPSE_SHARED_SECRET
          value: >-
            {{
              printf "{{ readfile \"/secrets/%s\" | quote }}" (
                 include "element-io.ess-library.init-secret-path" (
                     dict "root" $
                     "context" (dict
                       "secretProperty" .synapseSharedSecret
                       "initSecretKey" "MAS_SYNAPSE_SHARED_SECRET"
                       "defaultSecretName" (printf "%s-matrix-authentication-service" $.Release.Name)
                       "defaultSecretKey" "SYNAPSE_SHARED_SECRET"
                     )
                  )
                )
            }}
        - name: SYNAPSE_OIDC_CLIENT_SECRET
          value: >-
            {{
              printf "{{ readfile \"/secrets/%s\" | quote }}" (
                 include "element-io.ess-library.init-secret-path" (
                     dict "root" $
                     "context" (dict
                       "secretProperty" .synapseOIDCClientSecret
                       "initSecretKey" "MAS_SYNAPSE_OIDC_CLIENT_SECRET"
                       "defaultSecretName" (printf "%s-matrix-authentication-service" $.Release.Name)
                       "defaultSecretKey" "SYNAPSE_OIDC_CLIENT_SECRET"
                     )
                  )
                )
            }}
{{- end }}
{{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /config-templates
          name: plain-config
          readOnly: true
{{- range $secret := include "element-io.matrix-authentication-service.configSecrets" (dict "root" $ "context" .) | fromJsonArray }}
        - mountPath: /secrets/{{ tpl $secret $ }}
          name: "secret-{{ tpl $secret $ }}"
          readOnly: true
{{- end }}
        - mountPath: /conf
          name: rendered-config
          readOnly: false
      - name: db-wait
{{- with $.Values.matrixTools.image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ required "matrixTools.image.tag is required if no digest" .tag }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        command:
        - "/matrix-tools"
        - tcpwait
        - -address
        - {{ include "element-io.ess-library.postgres-host-port" (dict "root" $ "context" .postgres)}}
{{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
{{- /* This init container job is kept despite https://github.com/matrix-org/matrix-authentication-service/pull/2432 so as to have --prune */}}
      - name: config
        args: ["config", "sync", "--prune"]
{{- with .image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ required "matrixAuthenticationService.image.tag is required if no digest" .tag }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        env:
        {{- include "element-io.matrix-authentication-service.env" (dict "root" $ "context" .) | nindent 10 }}
{{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: "/config.yaml"
          name: rendered-config
          subPath: config.yaml
          readOnly: true
      containers:
      - name: matrix-authentication-service
        args: ["server"]
{{- with .image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ required "matrixAuthenticationService.image.tag is required if no digest" .tag }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        env:
        {{- include "element-io.matrix-authentication-service.env" (dict "root" $ "context" .) | nindent 10 }}
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        - containerPort: 8081
          protocol: TCP
          name: internal
{{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        startupProbe:
          httpGet:
            path: /health
            port: internal
            scheme: HTTP
          initialDelaySeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: internal
            scheme: HTTP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: internal
            scheme: HTTP
        volumeMounts:
        - mountPath: "/config.yaml"
          name: rendered-config
          subPath: config.yaml
          readOnly: true
{{- range $secret := include "element-io.matrix-authentication-service.configSecrets" (dict "root" $ "context" .) | fromJsonArray }}
        - mountPath: /secrets/{{ tpl $secret $ }}
          name: "secret-{{ tpl $secret $ }}"
          readOnly: true
{{- end }}
      volumes:
      - emptyDir:
          medium: Memory
        name: "rendered-config"
      - name: plain-config
        configMap:
          name: {{ $.Release.Name }}-matrix-authentication-service
{{- range $secret := include "element-io.matrix-authentication-service.configSecrets" (dict "root" $ "context" .) | fromJsonArray }}
      - secret:
          secretName: {{ tpl $secret $ }}
        name: secret-{{ tpl $secret $ }}
{{- end }}
{{- end -}}
{{- end -}}
