{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with .Values.matrixAuthenticationService -}}
{{- if .enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-matrix-authentication-service
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.matrix-authentication-service.labels" (dict "root" $ "context" .) | nindent 4 }}
data:
{{- with .additional }}
{{- range $key := (. | keys | uniq | sortAlpha) }}
{{- $prop := index $.Values.matrixAuthenticationService.additional $key }}
{{- if $prop.config }}
  user-{{ $key }}: {{ $prop.config | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- with required ".postgres.password is required" .postgres.password }}
{{- with .value }}
  POSTGRES_PASSWORD: {{ . | b64enc }}
{{- end }}
{{- end }}
{{- with required ".matrixAuthenticationService.encryptionSecret is required" .encryptionSecret }}
{{- with .value }}
  ENCRYPTION_KEY: {{ . | b64enc }}
{{- end }}
{{- end }}
{{- with required "privateKeys is required for Matrix Authentication Service" .privateKeys }}
{{- with required "rsa is required for Matrix Authentication Service" .rsa }}
{{- with .value }}
  RSA_PRIVATE_KEY: {{ . | b64enc }}
{{- end }}
{{- end }}
{{- with .ecdsaPrime256v1 }}
{{- with .value }}
  ECDSA_PRIME256V1_PRIVATE_KEY: {{ . | b64enc }}
{{- end }}
{{- end }}
{{- with .ecdsaSecp256k1 }}
{{- with .value }}
  ECDSA_SECP256K1_PRIVATE_KEY: {{ . | b64enc }}
{{- end }}
{{- end }}
{{- with .ecdsaSecp384r1 }}
{{- with .value }}
  ECDSA_SECP384R1_PRIVATE_KEY: {{ . | b64enc}}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
