{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with $.Values.postgresql -}}
{{- if (include "element-io.postgresql.enabled" (dict "root" $)) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "element-io.postgresql.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-postgresql
  namespace: {{ $.Release.Namespace }}
data:
{{- with .adminPassword.value }}
  ADMIN_PASSWORD: {{ . | b64enc }}
{{- end }}
{{- with .essPassword.value }}
  ESS_PASSWORD: {{ .| b64enc }}
{{- end }}
{{- end -}}
{{- end -}}
