{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}
{{- with $.Values.postgresql -}}
{{- if (include "element-io.postgresql.enabled" (dict "root" $)) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "element-io.postgresql.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-postgresql
  namespace: {{ $.Release.Namespace }}
  annotations:
    k8s.element.io/confighash: "{{ include (print $.Template.BasePath "/postgresql/secret.yaml") $ | sha1sum }}"
    k8s.element.io/logconfighash: "{{ include (print $.Template.BasePath "/postgresql/configmap.yaml") $ | sha1sum }}"
{{- with .annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  serviceName: {{ $.Release.Name }}-postgresql
  replicas: {{ .instances | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}-postgresql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "element-io.postgresql.labels" (dict "root" $ "context" .) | nindent 8 }}
      annotations:
        k8s.element.io/confighash: "{{ include (print $.Template.BasePath "/postgresql/secret.yaml") $ | sha1sum }}"
        k8s.element.io/logconfighash: "{{ include (print $.Template.BasePath "/postgresql/configmap.yaml") $ | sha1sum }}"
{{- with .annotations }}
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- include "element-io.ess-library.pods.commonSpec" (dict "root" $ "context" (dict "componentValues" . "key" "postgresql" "deployment" false)) | nindent 6 }}
      containers:
      - name: postgresql
{{- with .image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ .tag }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        env:
        {{- include "element-io.postgresql.env" (dict "root" $ "context" .) | nindent 8 }}
        args:
        {{ include "element-io.postgresql.args" (dict "root" $ "context" .) | nindent 8 }}
{{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["pg_ctl", "stop", "-D", "/var/lib/postgresql/data", "-w", "-t", "55", "-m", "fast"]
        readinessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "postgres", "-c", "SELECT 1"]
          initialDelaySeconds: 15
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "postgres", "-c", "SELECT 1"]
          initialDelaySeconds: 45
          timeoutSeconds: 2
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
{{- range $secret := include "element-io.postgresql.configSecrets" (dict "root" $ "context" .) | fromJsonArray }}
        - mountPath: /secrets/{{ tpl $secret $ }}
          name: "secret-{{ tpl $secret $ }}"
          readOnly: true
{{- end }}
        - name: config
          mountPath: /docker-entrypoint-initdb.d/init-ess-dbs.sh
          subPath: init-dbs.sh
        - name: database
          mountPath: /var/lib/postgresql/data
        - name: temp
          mountPath: /tmp
        - name: var-run
          mountPath: /var/run
      - name: postgres-init-password
{{- with .image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ .tag }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        command:
        - /bin/sh
        - -c
        - >
          export POSTGRES_PASSWORD=`cat /secrets/{{
  include "element-io.ess-library.init-secret-path" (
    dict "root" $ "context" (
      dict "secretProperty" .adminPassword
            "initSecretKey" "POSTGRESQL_ADMIN_PASSWORD"
            "defaultSecretName" (printf "%s-postgresql" $.Release.Name)
            "defaultSecretKey" "ADMIN_PASSWORD"
      )
    ) }}`;
          export POSTGRES_ESS_PASSWORD=`cat /secrets/{{
  include "element-io.ess-library.init-secret-path" (
    dict "root" $ "context" (
      dict "secretProperty" .essPassword
            "initSecretKey" "POSTGRESQL_ESS_PASSWORD"
            "defaultSecretName" (printf "%s-postgresql" $.Release.Name)
            "defaultSecretKey" "ESS_PASSWORD"
      )
    ) }}`;
          while ! pg_isready -h localhost -d postgres -U postgres; do echo "Postgres not yet ready"; sleep 1; done;
          echo "Postgres now ready, so changing password";
          psql -w -U postgres -h localhost
          -c "ALTER USER ess_user PASSWORD '"$POSTGRES_ESS_PASSWORD"'";
          trap : TERM INT; sleep 9999999999d & wait
        volumeMounts:
{{- range $secret := include "element-io.postgresql.configSecrets" (dict "root" $ "context" .) | fromJsonArray }}
        - mountPath: /secrets/{{ tpl $secret $ }}
          name: "secret-{{ tpl $secret $ }}"
          readOnly: true
{{- end }}
      - name: postgres-exporter
{{- with .postgresExporter.image -}}
{{- if .digest }}
        image: "{{ .registry }}/{{ .repository }}@{{ .digest }}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
{{- else }}
        image: "{{ .registry }}/{{ .repository }}:{{ .tag }}"
        imagePullPolicy: {{ .pullPolicy | default "Always" }}
{{- end }}
{{- end }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        ports:
        - name: metrics
          containerPort: 9187
        env:
        - name: DATA_SOURCE_URI
          value: "postgres?sslmode=disable"
        - name: DATA_SOURCE_USER
          value: "postgres"
        - name: PG_EXPORTER_METRIC_PREFIX
          value: metrics
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: temp
      - emptyDir: {}
        name: var-run
{{- range $secret := include "element-io.postgresql.configSecrets" (dict "root" $ "context" .) | fromJsonArray }}
      - secret:
          secretName: {{ tpl $secret $ }}
        name: secret-{{ tpl $secret $ }}
{{- end }}
      - name: config
        configMap:
          name: {{ $.Release.Name }}-postgresql
      - name: database
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-postgresql-data
{{- end }}
{{- end }}
