# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

serverName: ess.localhost

synapse:
  additional:
    00-userconfig.yaml:
      config: |
        push:
          jitter_dalay: 10
    01-other-user-config.yaml:
      configSecret:  "{{ $.Release.Name }}-ess-secrets"
      configSecretKey: "01-other-config.yaml"

  registrationSharedSecret:
    secret: "{{ $.Release.Name }}-ess-secrets"
    secretKey: registrationSharedSecret
  macaroon:
    secret: "{{ $.Release.Name }}-ess-secrets"
    secretKey: macaroon
  signingKey:
    secret: "{{ $.Release.Name }}-ess-secrets"
    secretKey: signingKey

  postgres:
    host: "{{ $.Release.Name }}-synapse-postgresql"
    user: synapse_user
    database: synapse_db
    password:
      secret: "{{ $.Release.Name }}-synapse-postgres-db"
      secretKey: password

  ingress:
    host: synapse.{{ $.Values.serverName }}
    tlsSecret: "{{ $.Release.Name }}-synapse-web-tls"

  tolerations:
    - key: context
      operator: Equal
      value: pytest
      effect: NoSchedule

  workers:
    sliding-sync:
      enabled: true
    media-repository:
      enabled: true

  haproxy:
    replicas: 1
    tolerations:
      - key: context
        operator: Equal
        value: pytest
        effect: NoSchedule

  redis:
    tolerations:
      - key: context
        operator: Equal
        value: pytest
        effect: NoSchedule

elementWeb:
  enabled: false
