# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

serverName: ess.localhost

synapse:
  additional:
    00-userconfig.yaml:
      config: |
        push:
          jitter_dalay: 10
    01-other-user-config.yaml:
      configSecret: "{{ $.Release.Name }}-synapse-secrets"
      configSecretKey: "01-other-user-config.yaml"

  extraEnv:
  - name: DEBUG_RENDERING
    value: "1"

  registrationSharedSecret:
    secret: "{{ $.Release.Name }}-synapse-secrets"
    secretKey: registrationSharedSecret

  postgres:
    host: "{{ $.Release.Name }}-synapse-postgresql"
    user: synapse_user
    database: synapse_db
    password:
      secret: "{{ $.Release.Name }}-synapse-postgres-db"
      secretKey: password

  ingress:
    host: synapse.{{ $.Values.serverName }}
    tlsSecret: "{{ $.Release.Name }}-synapse-web-tls"

  redis:
    annotations:
      has-no-service-monitor: "true"
  workers:
    sliding-sync:
      enabled: true
    media-repository:
      enabled: true

elementWeb:
  enabled: false

matrixAuthenticationService:
  enabled: false

wellKnownDelegation:
  enabled: false
