# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

global:
  baseDomain: ess.localhost

# To check that templating works against the ingress
serverName: "{{ $.Values.global.baseDomain }}"

synapse:
  enabled: false

elementWeb:
  enabled: false

wellKnownDelegation:
  ingress:
    tlsSecret: "{{ $.Release.Name }}-well-known-web-tls"
