# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

serverName: ess.localhost

elementWeb:
  enabled: false

synapse:
  ingress:
    host: synapse.ess.localhost

  additional:
    0-guestConfig:
      config: |
        allow_guest_access: true
    1-retentionSettings:
      config: |
        retention_policy:
          enabled: true
    2-userProvided:
      configSecret: my-user-config
      configSecretKey: shared.yaml
  registrationSharedSecret:
    value: CHANGEME-ooWo6jeidahhei3Hae0eer9U
  macaroon:
    value: CHANGEME-eek3Eigoh8ux8laeTingeej1
  signingKey:
    value: ed25519 0 bNQOzBUDszff7Ax81z6w0uZ1IPWoxYaazT7emaZEfpw

  postgres:
    host: ess-postgres
    user: synapse_user
    database: synapse
    password:
      secret: ess-postgres
      secretKey: password
