# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

# This value file is not complete on its own.
# It is a mixin to be used with other values file to enable
# usage of the test cluster

elementWeb:
  ingress:
    tlsSecret: ess-selfsigned

  tolerations:
  - key: context
    operator: Equal
    value: pytest
    effect: NoSchedule

synapse:
  ingress:
    tlsSecret: ess-selfsigned

  tolerations:
  - key: context
    operator: Equal
    value: pytest
    effect: NoSchedule

  haproxy:
    tolerations:
    - key: context
      operator: Equal
      value: pytest
      effect: NoSchedule

  redis:
    tolerations:
    - key: context
      operator: Equal
      value: pytest
      effect: NoSchedule
