{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with $.Values.matrixRTC -}}
{{- if .enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-matrix-rtc-sfu-jwt
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.matrix-rtc-sfu-jwt.labels" (dict "root" $ "context" .) | nindent 4 }}
type: Opaque
data:
{{- if not .keysYaml }}
  {{- if $.Values.matrixRTC.sfu.enabled -}}
    {{- include "element-io.ess-library.check-credential" (dict "root" $ "context" (dict "secretPath" "matrixRTC.livekitAuth.secret" "initIfAbsent" true)) }}
  {{- end }}
{{- else }}
  {{- include "element-io.ess-library.check-credential" (dict "root" $ "context" (dict "secretPath" "matrixRTC.livekitAuth.keysYaml" "initIfAbsent" false)) }}
{{- end }}
{{- with .livekitAuth -}}
  {{- with .keysYaml }}
    {{- with .value }}
  LIVEKIT_KEYS_YAML: {{ . | b64enc }}
    {{- end -}}
  {{- end -}}
  {{- with .secret }}
    {{- with .value }}
  LIVEKIT_SECRET: {{ . | b64enc }}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
