{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with .Values.synapse -}}
{{- if .enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "element-io.synapse.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-synapse
  namespace: {{ $.Release.Namespace }}
data:
{{- with .additional }}
{{- range $key := (. | keys | uniq | sortAlpha) }}
{{- $prop := index $.Values.synapse.additional $key }}
{{- if $prop.config }}
  {{ $key }}: {{ $prop.config | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- include "element-io.ess-library.check-credential" (dict "root" $ "context" (dict "secretPath" "synapse.macaroon" "secretProperty" .macaroon)) -}}
{{- with .macaroon.value }}
  MACAROON: {{ . | b64enc }}
{{- end }}
{{- include "element-io.ess-library.check-credential" (dict "root" $ "context" (dict "secretPath" "synapse.postgres.password" "secretProperty" .postgres.password)) -}}
{{- with .postgres.password.value }}
  POSTGRES: {{ . | b64enc }}
{{- end }}
{{- include "element-io.ess-library.check-credential" (dict "root" $ "context" (dict "secretPath" "synapse.registrationSharedSecret" "secretProperty" .registrationSharedSecret)) -}}
{{- with .registrationSharedSecret.value }}
  REGISTRATION_SHARED_SECRET: {{ . | b64enc }}
{{- end }}
{{- include "element-io.ess-library.check-credential" (dict "root" $ "context" (dict "secretPath" "synapse.signingKey" "secretProperty" .signingKey)) -}}
{{- with .signingKey.value }}
  SIGNING_KEY: {{ .| b64enc }}
{{- end }}
{{- end -}}
{{- end -}}
