{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with .Values.synapse -}}
{{- if and .enabled .checkConfigHook.enabled -}}
{{- $enabledWorkers := (include "element-io.synapse.enabledWorkers" (dict "root" $)) | fromJson }}
{{- $processType := "check-config-hook" }}
{{- $perProcessRoot := merge (dict "processType" $processType "isHook" true) ($.Values.synapse | deepCopy) (.checkConfigHook | deepCopy)}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-synapse-check-config-hook
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- with .checkConfigHook.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "element-io.synapse-hook.labels" (dict "root" $ "context" .checkConfigHook) | nindent 4 }}
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  {{- include "element-io.synapse.pod-template" (dict "root" $ "context" (merge $perProcessRoot (dict "isHook" true))) | nindent 2 }}
{{- end }}
{{- end }}
