{{- /*
Copyright 2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- with $.Values.postgres -}}
{{- if (include "element-io.postgres.enabled" (dict "root" $)) }}
{{- if or .adminPassword.value (include "element-io.postgres.anyEssPasswordHasValue" (dict "root" $ "context" .)) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "element-io.postgres.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-postgres
  namespace: {{ $.Release.Namespace }}
data:
{{- with .adminPassword.value }}
  ADMIN_PASSWORD: {{ . | b64enc }}
{{- end }}
{{- range $key := (.essPasswords | keys | uniq | sortAlpha) }}
{{- $prop := index $.Values.postgres.essPasswords $key }}
{{- with $prop.value }}
  ESS_PASSWORD_{{ $key | upper }}: {{ .| b64enc }}
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
