{{- /*
Copyright 2024-2025 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}
{{- with .Values.elementWeb -}}
{{- if .enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "element-io.element-web.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-element-web-nginx
  namespace: {{ $.Release.Namespace }}
data:
  default.conf: |-
    {{- ($.Files.Get "configs/element-web/default.conf") | nindent 4 }}

  # Customisations that we do at the http rather than the server level
  http_customisations.conf: |-
    {{- ($.Files.Get "configs/element-web/http_customisations.conf") | nindent 4 }}

  # For repeated inclusion in default.conf because the add_header directives need to be repeated as per
  # https://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header as they are only inherited from
  # the server block iff there's no add_header directives in the location block
  security_headers.conf: |-
    {{- ($.Files.Get "configs/element-web/security_headers.conf") | nindent 4 }}

{{- end }}
{{- end }}
