# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v2
name: matrix-stack
description: A Helm meta-chart for deploying a Matrix Stack from Element
type: application
version: "0.7.4-dev"
dependencies: []
