# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

synapse:
  additional:
    00-userconfig.yaml:
      config: |
        push:
          jitter_dalay: 10
    01-other-user-config.yaml:
      configSecret: "{{ $.Release.Name }}-synapse-secrets"
      configSecretKey: "01-other-user-config.yaml"

  extraEnv:
  - name: DEBUG_RENDERING
    value: "1"

  ingress:
    host: synapse.{{ $.Values.serverName }}
    tlsSecret: "{{ $.Release.Name }}-synapse-web-tls"

  redis:
    annotations:
      has-no-service-monitor: "true"
  workers:
    sliding-sync:
      enabled: true
    media-repository:
      enabled: true
