# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

synapse:
  ingress:
    host: synapse.{{ $.Values.serverName }}
    tlsSecret: "{{ $.Release.Name }}-synapse-web-tls"

  checkConfigHook:
    annotations:
      has-no-service-monitor: "true"

  redis:
    annotations:
      has-no-service-monitor: "true"

    podSecurityContext:
      runAsGroup: 0

  podSecurityContext:
    runAsGroup: 0

haproxy:
  podSecurityContext:
    runAsGroup: 0

postgres:
  podSecurityContext:
    runAsGroup: 0