# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Artifact Hub Metadata

on:
  pull_request_target:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  artifact-hub:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: oras-project/setup-oras@v1

    - name: ORAS Login
      env:
        ORAS_USERNAME: ${{ github.actor }}
        ORAS_PASSWORD: ${{ github.token }}
      run: |
          oras login ghcr.io -u $ORAS_USERNAME -p $ORAS_PASSWORD

    - name: Push artifact-hub
      run: |
        oras push \
          oci://ghcr.io/${{ github.repository }}:artifacthub.io \
          --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
          artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml
