# Copyright 2025 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Changelog
on: [pull_request]

jobs:
  check-newsfile:
    if: ${{ (github.base_ref == 'main'  || contains(github.base_ref, 'release-')) && github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.sha}}

      - uses: matrix-org/setup-python-poetry
        with:
          python-version: "3.x"
          poetry-version: "1.8.5"

      - name: Run towncrier
        run: |
          # Fix/workaround for "detected dubious ownership in repository"
          git config --global --add safe.directory "${GITHUB_WORKSPACE}" 
          scripts/check_newsfragment.sh ${{ github.event.number }}
