# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Licensing checks

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  reuse-compliance-check:
    runs-on: cpu-s
    container:
      image: ghcr.io/${{ github.repository }}/ci-runner
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Define a cache for the virtual environment based on the dependencies lock file
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Install venv
      run: |
        poetry env info
        poetry install
        echo "$(poetry env info -p)/bin" >> "${GITHUB_PATH}"

    - name: reuse-lint
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        reuse --version
        reuse lint

    - name: SPDX checks
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        reuse --version
        reuse spdx | ./scripts/spdx_checks.py
