# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Licensing checks

on:
  pull_request_target:
  push:
    branches:
    - main

permissions:
  contents: read
  packages: read

jobs:
  reuse-compliance-check:
    runs-on: cpu-s
    container:
      image: ghcr.io/${{ github.repository }}/ci-runner
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: reuse-lint
      run: reuse lint
