# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Licensing checks

on:
  pull_request_target:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: matrix-org/setup-python-poetry@gaelg/poetry-venv
      with:
        poetry-version: "1.8.5"
        python-version: "3.x"

    - name: Load poetry path
      run: |
        echo "$(poetry env info -p)/bin" >> "${GITHUB_PATH}"

    - name: reuse-lint
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        reuse --version
        reuse lint

    - name: SPDX checks
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        reuse --version
        reuse spdx | ./scripts/spdx_checks.py
