# Copyright 2024 New Vector Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Run Pytest tests

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-component:
        - element-web
        - matrix-authentication-service
        - synapse
        - well-known-delegation
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: matrix-org/setup-python-poetry
      with:
        poetry-version: "1.8.5"
        python-version: "3.x"

    - uses: engineerd/setup-kind@v0.6.2
      with:
        config: tests/integration/fixtures/files/clusters/kind.yml
        name: kind-ess-helm

    - uses: azure/setup-helm@v4.2.0

    - name: Test with pytest
      run: |
        cp tests/integration/fixtures/files/clusters/audit-policy.yml /dind-job-shared/audit-policy.yml
        . tests/integration/env/${{ matrix.test-component }}.rc
        PYTEST_KEEP_CLUSTER=1 poetry run pytest tests/integration

    - name: Export logs
      if: ${{ failure() }}
      shell: bash
      run: |
        kind export logs --name ess-helm ./ess-helm-logs
        kind export kubeconfig --name ess-helm
        ns=$(kubectl --context kind-ess-helm get ns -l app.kubernetes.io/managed-by=pytest  -o jsonpath='{.items[].metadata.name}')
        resources=("pods" "deployments" "statefulsets" "services" "configmaps" "secrets" "ingresses" "persistentvolumes" "persistentvolumeclaims")
        for i in "${resources[@]}"; do
          kubectl --context kind-ess-helm get $i -n $ns > ./ess-helm-logs/$i.txt
          echo "----" >> ./ess-helm-logs/$i.txt
          kubectl --context kind-ess-helm get $i -o yaml -n $ns >> ./ess-helm-logs/$i.txt
        done
        kubectl --context kind-ess-helm get events --sort-by=.metadata.creationTimestamp -n $ns > ./ess-helm-logs/events.txt
        kind delete cluster --name ess-helm

    - name: Upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: ess-helm-logs-${{ matrix.test-component }}
        path: ess-helm-logs
        retention-days: 1
