{{- /*
Copyright 2024 New Vector Ltd

SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
*/ -}}

{{- if or $.Values.synapse.enabled $.Values.wellKnownDelegation.enabled -}}
{{- with .Values.haproxy -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "element-io.haproxy.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-haproxy
  namespace: {{ $.Release.Namespace }}
data:
  haproxy.cfg: |
    {{- tpl ($.Files.Get "configs/haproxy/haproxy.cfg.tpl") (dict "root" $ "context" .) | nindent 4 }}
  429.http: |
    HTTP/1.0 429 Too Many Requests
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/html
    access-control-allow-origin: *
    access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization

    <html><body><h1>429 Too Many Requests</h1>
    No server is available to handle this request.
    </body></html>
{{- end -}}
{{- end -}}
